# Generated by Django 3.2.23 on 2023-12-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('Товар', 'Товар'), ('Услуга', 'Услуга')], max_length=6)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
